#!/usr/bin/env node
/* Fetches the Démosphère Bruxelles iCal feed and regenerates data/auto-events.json.
 * Runs in GitHub Actions on a schedule (see .github/workflows/update-events.yml).
 * No dependencies — plain Node 18+.
 *
 * Usage:
 *   node scripts/update-events.js               # fetch live feed
 *   node scripts/update-events.js path/to.ics   # parse a local file (for testing)
 */

const fs = require("fs");
const path = require("path");

const FEED_URL = "https://bxl.demosphere.net/events.ics";
const OUT_FILE = path.join(__dirname, "..", "data", "auto-events.json");

// Only keep events whose title matches one of these (case-insensitive) —
// the feed also contains talks, expos, workshops. Edit to taste.
const INCLUDE_KEYWORDS = [
  "rassemblement", "manif", "marche", "mars ", "grève", "greve", "staking",
  "action", "actie", "blocage", "blokkade", "piquet", "picket", "protest",
  "betoging", "mobilisation", "mobilisatie", "occupation", "bezetting",
  "critical mass", "sit-in", "die-in", "cortège", "optocht", "demonstration",
];

// ---------- iCal parsing ----------
function unfold(ics) {
  // RFC 5545: lines starting with space/tab continue the previous line
  return ics.replace(/\r?\n[ \t]/g, "");
}

function unescape(v) {
  return v.replace(/\\n/g, "\n").replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\\\/g, "\\");
}

function parseICS(ics) {
  const events = [];
  const blocks = unfold(ics).split("BEGIN:VEVENT").slice(1);
  for (const block of blocks) {
    const body = block.split("END:VEVENT")[0];
    const ev = {};
    for (const line of body.split(/\r?\n/)) {
      const m = line.match(/^([A-Z-]+)(?:;[^:]*)?:(.*)$/);
      if (m) ev[m[1]] = unescape(m[2].trim());
    }
    if (ev.DTSTART && ev.SUMMARY) events.push(ev);
  }
  return events;
}

// Convert an iCal UTC timestamp (YYYYMMDDTHHMMSSZ) to Brussels local date/time.
function toBrussels(dt) {
  const m = dt.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);
  if (!m) return null;
  const utc = new Date(Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5]));
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "Europe/Brussels",
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit", hour12: false,
  }).formatToParts(utc).reduce((o, p) => ((o[p.type] = p.value), o), {});
  return {
    date: `${parts.year}-${parts.month}-${parts.day}`,
    time: `${parts.hour === "24" ? "00" : parts.hour}:${parts.minute}`,
  };
}

function matchesKeywords(title) {
  const t = title.toLowerCase();
  return INCLUDE_KEYWORDS.some((k) => t.includes(k));
}

// ---------- main ----------
async function getICS() {
  const localFile = process.argv[2];
  if (localFile) return fs.readFileSync(localFile, "utf8");
  const res = await fetch(FEED_URL, { headers: { "User-Agent": "brussels-protest-tracker (github pages site)" } });
  if (!res.ok) throw new Error(`Feed returned HTTP ${res.status}`);
  return await res.text();
}

(async () => {
  const ics = await getICS();
  const raw = parseICS(ics);

  const events = raw
    .map((ev) => {
      const when = toBrussels(ev.DTSTART);
      if (!when) return null;
      const location = (ev.LOCATION || "")
        .replace(/\s*\n\s*/g, ", ")
        .replace(/,\s*,+/g, ",")
        .replace(/^[\s,]+|[\s,]+$/g, "")
        .trim();
      return {
        id: (ev.UID || ev.URL || ev.SUMMARY).replace(/^https?:\/\//, "").replace(/[^\w]+/g, "-"),
        title: ev.SUMMARY,
        date: when.date,
        time: when.time,
        location: location || "Brussels (see event page)",
        organizer: "",
        cause: "",
        source: ev.URL || ev.UID || FEED_URL,
        sourceName: "Démosphère Bruxelles (auto)",
        notes: "",
      };
    })
    .filter(Boolean)
    .filter((e) => matchesKeywords(e.title))
    .sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time));

  const out = {
    meta: {
      generated: new Date().toISOString().slice(0, 10),
      source: FEED_URL,
      note: "AUTO-GENERATED by scripts/update-events.js — do not edit by hand; changes will be overwritten.",
    },
    events,
  };

  fs.writeFileSync(OUT_FILE, JSON.stringify(out, null, 2) + "\n");
  console.log(`Wrote ${events.length} events to ${OUT_FILE} (${raw.length} in feed, rest filtered by keywords).`);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
